---
title: "Collings_Assignment_6"
author: "KC Collings"
date: "2025-10-29"
output: html_document
---

#Introduction 

In the study by Dharmasiri et al., (2025) the relationship between song complexity and age was assessed in a population of male European starlings, Sturnus vulgaris. The aim of this study was to determine whether aspects of song (repertoire size and average song bout length) act as a signal of age over a 1-year period within a wild population of starlings. Repertoire size is defined as being the number of unique phrase types a bird sings, and song bout length is defined as the average duration of an individual birds song (Ball, & Hulse, 1998). European starlings are known for their song complexity: they have large repertoires and sing long song bouts (Eens et al., 1991). They are also open-ended learners, meaning that they can learn new songs and add and remove songs from their repertoire throughout their lifetime (Brenowitz & Beecher, 2005). Previous research has shown that aspects of song complexity act as an indicator of age between second year (born the previous year) and after second year (born more than a year ago) birds, but whether this trend continues across differently aged after second year birds differs across species (Vaytina & Shitkov, 2019). In the current study, only after second year birds were evaluated. A previous study on a captive population of starlings has shown that song complexity does not signal age over a 1-year period in after second year birds (Eens et al., 1992), but whether this pattern is also seen within wild populations is not known.   

#Methods 

A total of 8 birds were used in this study, sampled from an established population living and breeding on the campus of Saint Mary's University in Halifax, Nova Scotia. Birds were captured in their nest box to be banded with a unique colour combination of bands (for reidentification purposes) and 7 hackle (throat) feathers were sampled. Age was then determined by measuring the mean length of the iridescence portion of the hackle feathers. This was done using a ruler under a dissecting microscope; from the average length of the iridescence, they could determine whether males were  second year or after second year (and only after second year birds were included in this study). Individual male song was then recorded daily from outside their nestbox from early February throughout their spring breeding season until a minimum of 27 song bouts were recorded for each of the birds evaluated. This was done using a shotgun microphone and digital recorder, and repeated across 2 years. Song was then analyzed to determine repertoire size (by evaluating how many unique phrase types were within the 27 bouts) and song bout length (by measuring the duration of each of the 27 bouts). This was done using raven pro software which visualizes the song as a spectrogram and has tools to measure it (Dharmasiri et al., 2025). 

#Conclusions

Figure 1 displays repertoire size from 8 male European starlings over a 1-year period, on the x axis is the year of song recording and on the y axis is the repertoire size. Note that there were 8 males evaluated, but 2 of them followed the exact same pattern (increasing from 62 to 67 songs) so it appears as though there are only 7 points. Repertoire size increased for 6 of 8 males, remained the same for 1 of 8 males, and decreased for 1 of 8 males. However, overall, there were no significant changes in repertoire size detected.  

![Figure 1  Repertoire size of 8 male European Starlings, Strurnus vulgaris, 
recorded over a 1-year period.](/users/kc/desktop/repertoire_size.png)

Figure 2 displays mean bout length from the same 8 male European starlings over a 1-year period, on the x axis is the year of song recording and on the y axis is mean bout length. Mean song bout length increased for 4 of 8 males and decreased for 4 of 8 males. However, overall, there were no significant changes in song bout length detected.

![Figure 2  Mean song bout length of 8 male European Starlings, Strurnus 
vulgaris, recorded over a 1-year period.](/users/kc/desktop/bout_length.png)
